POST http://127.0.0.1:9011/api/login
content-type: application/json
Authorization: API Token

{
  "loginId": "Danny",
  "password": "danielbrault",
  "applicationId": "458396b0-d890-4e73-9c5a-df7d80249a30",
  "noJWT" : false
}
###

GET http://100.64.98.56:3000/movie
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlhzQ2ZCTDhYNFVCb2ZpbDJMbHZkZEx3WmJyZyJ9.eyJhdWQiOiI0NTgzOTZiMC1kODkwLTRlNzMtOWM1YS1kZjdkODAyNDlhMzAiLCJleHAiOjE2MzM3NzYzNzUsImlhdCI6MTYzMzc3Mjc3NSwiaXNzIjoiYWNtZS5jb20iLCJzdWIiOiI4ZTZlYjFkMy04Njk2LTQ2Y2UtYTAxOC0wYzEyYjllN2Q5YTUiLCJqdGkiOiI0N2JhOTQ4MC0zMjcyLTQ0MGItYmNiNS0xYzE0MGQ0N2Y0N2YiLCJhdXRoZW50aWNhdGlvblR5cGUiOiJQQVNTV09SRCIsImVtYWlsIjoiZGFuaWVsYnJhdWx0QHRlbGV3b3JtLnVzIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6IkRhbm55IiwiYXBwbGljYXRpb25JZCI6IjQ1ODM5NmIwLWQ4OTAtNGU3My05YzVhLWRmN2Q4MDI0OWEzMCIsInJvbGVzIjpbImVtcGxveWUiXX0.QaxzS6VDX4TuhRy586iRFxp1rAWky0OxLAW_1LWalbQ68XH0LJjGnyzFpZBC8ep1RcT20l4L9YkSZl_p9mZmtowPxEoSEyIhEJPbAxomaLaha6KDljSJTIdDGtNQFUPUUWGQyts83IOAjFQWGjgnURTqJ6z2arMJaNwuQEs0mg1A-5OW5cD6c8X-PP2qfQnrQfk5z3q804eN9gNDzcAlPVYncb9kWrQsjZIs4iuesEStv_1gmvT63o9BEt1xWe_p8UmEtOFjm15Dp0H4Pkinhmd9SfAhV2qpwXPaTCCjGnQKVDia3UnFuj541wzUlbQ3zVlUnMWTgy7Wq7KAbM0yfA