GET http://127.0.0.1:3000

###

GET http://127.0.0.1:3000/movie


###

POST http://127.0.0.1:3000/movie
Content-Type: application/json

{
    "nom": "Brown",
    "prenom": "Theodor",
    "nationalite": ["fr","gb"] 
}

###
POST http://127.0.0.1:3000/movie
Content-Type: application/json

{
    "nom": "Hoang",
    "prenom": "Tieu Ly",
    "nationalite": ["fr"] 
}

###
DELETE http://127.0.0.1:3000/movie/a22f4d8f-dfbd-4d55-be5f-08585f62e97a


###

GET http://127.0.0.1:3000/movie/film/2b40a5ea-1394-49f7-9643-51bcff249434